project:
  type: book

  output-dir: docs

book:
  title: "Rust for R Developers"
  subtitle: Cascadia R Conference, 2025
  author: "Josiah Parry"
  date: "2025-06-20"
  site-url: https://josiahparry.github.io/2025-cascadia-rust-for-r-devs/
  repo-url: https://github.com/JosiahParry/2025-cascadia-rust-for-r-devs/
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - part: intro-to-rust-for-r-devs/index.qmd
      chapters:
        # - intro-to-rust-for-r-devs/index.qmd
        - intro-to-rust-for-r-devs/why-rust.qmd
        - intro-to-rust-for-r-devs/hello-world.qmd
        - intro-to-rust-for-r-devs/types.qmd
        - intro-to-rust-for-r-devs/fizz-buzz.qmd
        - intro-to-rust-for-r-devs/collections.qmd
        - intro-to-rust-for-r-devs/for-loops.qmd
        - intro-to-rust-for-r-devs/mutability.qmd
        - intro-to-rust-for-r-devs/mutable-vectors.qmd
        - intro-to-rust-for-r-devs/is-odd.qmd
        - intro-to-rust-for-r-devs/references-slices.qmd
        - intro-to-rust-for-r-devs/iterators.qmd
        - intro-to-rust-for-r-devs/iter-map.qmd
        - intro-to-rust-for-r-devs/structs.qmd
        - intro-to-rust-for-r-devs/struct-methods.qmd
        - intro-to-rust-for-r-devs/enums.qmd
        - intro-to-rust-for-r-devs/options.qmd
        - intro-to-rust-for-r-devs/parallelize.qmd
    - part: building-rust-based-r-pkgs/index.qmd
      chapters:
        - building-rust-based-r-pkgs/ffi.qmd
        - building-rust-based-r-pkgs/extendr.qmd
        - building-rust-based-r-pkgs/objective.qmd
        - building-rust-based-r-pkgs/hello-world.qmd
        - building-rust-based-r-pkgs/extendr-structure.qmd
        - building-rust-based-r-pkgs/extendr-dx.qmd
        - building-rust-based-r-pkgs/rust-deps.qmd
        - building-rust-based-r-pkgs/first-fn.qmd
        - building-rust-based-r-pkgs/encode.qmd
        - building-rust-based-r-pkgs/throwing-errors.qmd
        - building-rust-based-r-pkgs/vectorize.qmd
        - building-rust-based-r-pkgs/r-type-system.qmd
        - building-rust-based-r-pkgs/type-mapping-p1.qmd
        - building-rust-based-r-pkgs/using-extendr-types.qmd
        - building-rust-based-r-pkgs/error-handling.qmd
        - building-rust-based-r-pkgs/na-handling.qmd
        - building-rust-based-r-pkgs/enums.qmd
        - building-rust-based-r-pkgs/geohash-nb.qmd
        - building-rust-based-r-pkgs/vectorize-neighbor.qmd
        - building-rust-based-r-pkgs/decode.qmd

format:
  html:
    theme:
      - cosmo
    # number-sections: false
    number-depth: 1
    highlight-style: github
    callout-appearance: simple
